const preloadedLevels = {
    "A1 - Level 1": [
        { word: "answer", trans: "menjawab", def: "Memberikan tanggapan lisan atau tulisan." },
        { word: "autumn", trans: "musim gugur", def: "Musim peralihan sebelum musim dingin." },
        { word: "bread", trans: "roti", def: "Makanan olahan gandum yang dipanggang." },
        { word: "build", trans: "membangun", def: "Membuat konstruksi fisik atau gedung." },
        { word: "climb", trans: "memanjat", def: "Bergerak naik menggunakan tangan dan kaki." },
        { word: "comb", trans: "sisir", def: "Alat bergerigi untuk merapikan rambut." },
        { word: "doubt", trans: "ragu", def: "Ketidakyakinan terhadap suatu kebenaran." },
        { word: "eight", trans: "delapan", def: "Angka genap setelah angka tujuh." },
        { word: "fruit", trans: "buah", def: "Bagian tumbuhan berbiji yang dikonsumsi." },
        { word: "half", trans: "setengah", def: "Satu dari dua bagian terbagi sama." },
        { word: "head", trans: "kepala", def: "Bagian tubuh atas tempat otak berada." },
        { word: "hour", trans: "jam", def: "Satuan waktu enam puluh menit." },
        { word: "island", trans: "pulau", def: "Daratan yang dikelilingi oleh air." },
        { word: "juice", trans: "jus", def: "Sari cairan dari perasan buah segar." },
        { word: "knee", trans: "lutut", def: "Sendi penghubung paha dan tungkai kaki." },
        { word: "knife", trans: "pisau", def: "Alat berbilah tajam untuk memotong." },
        { word: "knock", trans: "mengetuk", def: "Memukul pintu sebagai tanda bertamu." },
        { word: "know", trans: "tahu", def: "Memahami kenyataan atas suatu hal." },
        { word: "lamb", trans: "anak domba", def: "Ternak domba yang masih berusia muda." },
        { word: "listen", trans: "mendengarkan", def: "Memusatkan telinga pada sumber suara." },
        { word: "night", trans: "malam", def: "Waktu gelap setelah terbenam matahari." },
        { word: "thumb", trans: "ibu jari", def: "Jari tangan terpendek dan paling tebal." },
        { word: "walk", trans: "berjalan", def: "Melangkah maju dengan kedua kaki." },
        { word: "write", trans: "menulis", def: "Menuangkan kata pada media kertas." },
        { word: "wrong", trans: "salah", def: "Kondisi tidak tepat atau menyimpang." }
    ],
    "A1 - Level 2": [
        { word: "apple", trans: "apel", def: "Buah bulat renyah berkulit merah." },
        { word: "bottle", trans: "botol", def: "Wadah penyimpanan air berleher sempit." },
        { word: "butter", trans: "mentega", def: "Produk olahan lemak susu padat." },
        { word: "carrot", trans: "wortel", def: "Sayuran umbi kerucut berwarna oranye." },
        { word: "coffee", trans: "kopi", def: "Minuman seduh dari biji sangrai." },
        { word: "dinner", trans: "makan malam", def: "Santapan utama pada waktu malam." },
        { word: "egg", trans: "telur", def: "Cikal bakal unggas bercangkang keras." },
        { word: "follow", trans: "mengikuti", def: "Berjalan di belakang pihak lain." },
        { word: "glass", trans: "gelas", def: "Wadah minum berbahan dasar kaca." },
        { word: "grass", trans: "rumput", def: "Tumbuhan hijau penutup tanah lapangan." },
        { word: "happy", trans: "senang", def: "Perasaan hati yang dipenuhi gembira." },
        { word: "letter", trans: "surat", def: "Pesan tertulis yang dikirimkan pos." },
        { word: "middle", trans: "tengah", def: "Titik pusat antara dua tepi." },
        { word: "puddle", trans: "kubangan", def: "Genangan air kecil di atas tanah." },
        { word: "puppy", trans: "anak anjing", def: "Anjing piaraan yang masih kecil." },
        { word: "rabbit", trans: "kelinci", def: "Hewan mamalia bertelinga panjang pelompat." },
        { word: "really", trans: "sungguh", def: "Menegaskan kenyataan yang sebenar-benarnya." },
        { word: "rubber", trans: "penghapus", def: "Alat pengoreksi coretan pensil kertas." },
        { word: "spoon", trans: "sendok", def: "Alat makan cekung bertangkai pegangan." },
        { word: "summer", trans: "musim panas", def: "Musim bercuaca terik dan cerah." },
        { word: "swimming", trans: "berenang", def: "Aktivitas mengapung bergerak di air." },
        { word: "tennis", trans: "tenis", def: "Olahraga memukul bola melintasi net." },
        { word: "traffic", trans: "lalu lintas", def: "Arus kendaraan di badan jalan raya." },
        { word: "village", trans: "desa", def: "Permukiman penduduk di kawasan luar kota." },
        { word: "yellow", trans: "kuning", def: "Warna terang seperti buah pisang matang." }
    ],
    "A1 - Level 3": [
        { word: "beautiful", trans: "indah", def: "Rupawan dan sedap dipandang mata." },
        { word: "bought", trans: "membeli", def: "Memperoleh barang dengan menukar uang." },
        { word: "breakfast", trans: "sarapan", def: "Makanan pertama pada pagi hari." },
        { word: "brother", trans: "saudara laki-laki", def: "Kerabat kandung berjenis kelamin pria." },
        { word: "busy", trans: "sibuk", def: "Memiliki jadwal kerjaan yang padat." },
        { word: "chocolate", trans: "cokelat", def: "Olahan kudapan dari biji kakao." },
        { word: "clothes", trans: "pakaian", def: "Kain penutup dan pelindung badan." },
        { word: "cousin", trans: "sepupu", def: "Anak kandung paman atau bibi." },
        { word: "daughter", trans: "anak perempuan", def: "Keturunan kandung berjenis kelamin wanita." },
        { word: "doctor", trans: "dokter", def: "Tenaga medis ahli pemeriksa kesehatan." },
        { word: "family", trans: "keluarga", def: "Unit sosial terkecil berikatan darah." },
        { word: "february", trans: "februari", def: "Bulan kedua dalam kalender masehi." },
        { word: "friend", trans: "teman", def: "Orang yang dikenal akrab di luar kerabat." },
        { word: "guitar", trans: "gitar", def: "Instrumen petik berbadan resonansi kayu." },
        { word: "minute", trans: "menit", def: "Satuan waktu sepanjang enam puluh detik." },
        { word: "people", trans: "orang-orang", def: "Kumpulan individu sesama umat manusia." },
        { word: "question", trans: "pertanyaan", def: "Ungkapan kalimat meminta kejelasan informasi." },
        { word: "school", trans: "sekolah", def: "Lembaga penyelenggara kegiatan pendidikan resmi." },
        { word: "shoes", trans: "sepatu", def: "Alas pelindung telapak kaki luar." },
        { word: "stomach", trans: "perut", def: "Rongga badan tempat pencernaan makanan." },
        { word: "sugar", trans: "gula", def: "Butiran pemanis alami dari tebu." },
        { word: "thursday", trans: "kamis", def: "Hari kelima dalam perputaran sepekan." },
        { word: "tuesday", trans: "selasa", def: "Hari ketiga dalam perputaran sepekan." },
        { word: "wednesday", trans: "rabu", def: "Hari keempat dalam perputaran sepekan." },
        { word: "women", trans: "wanita", def: "Kaum perempuan dewasa dalam masyarakat." }
    ],
    "A2 - Level 1": [
        { word: "ache", trans: "sakit", def: "Rasa nyeri menahun pada organ tubuh." },
        { word: "calm", trans: "tenang", def: "Kondisi damai tanpa adanya gangguan." },
        { word: "castle", trans: "kastel", def: "Benteng pertahanan batu masa lalu." },
        { word: "caught", trans: "menangkap", def: "Menggapai benda bergerak dengan tangan." },
        { word: "debt", trans: "utang", def: "Tanggungan dana yang harus dikembalikan." },
        { word: "design", trans: "desain", def: "Rancangan gambar suatu produk karya." },
        { word: "ghost", trans: "hantu", def: "Penampakan sosok halus tak kasat mata." },
        { word: "guess", trans: "menebak", def: "Memperkirakan dugaan tanpa bukti valid." },
        { word: "guest", trans: "tamu", def: "Orang luar yang diundang berkunjung." },
        { word: "guide", trans: "pemandu", def: "Penunjuk jalan rombongan pariwisata." },
        { word: "headache", trans: "sakit kepala", def: "Sensasi berdenyut di tempurung kepala." },
        { word: "height", trans: "tinggi", def: "Jarak tegak vertikal dari dasar." },
        { word: "honest", trans: "jujur", def: "Berkata lurus sesuai dengan fakta." },
        { word: "honour", trans: "kehormatan", def: "Penghargaan atas kemuliaan budi pekerti." },
        { word: "sign", trans: "tanda", def: "Papan simbol petunjuk di jalan." },
        { word: "straight", trans: "lurus", def: "Garis memanjang searah tanpa belokan." },
        { word: "sword", trans: "pedang", def: "Senjata tajam berbilah logam panjang." },
        { word: "talk", trans: "berbicara", def: "Menyampaikan kata-kata melalui suara mulut." },
        { word: "taught", trans: "mengajar", def: "Mentransfer wawasan ilmu kepada murid." },
        { word: "thought", trans: "pikiran", def: "Gagasan yang diproses akal budi." },
        { word: "tongue", trans: "lidah", def: "Organ pencecap rasa di dalam mulut." },
        { word: "weight", trans: "berat", def: "Bobot timbangan massa suatu benda." },
        { word: "whistle", trans: "peluit", def: "Alat tiup bersuara nyaring melengking." },
        { word: "wrap", trans: "membungkus", def: "Melapisi barang memakai kertas penutup." },
        { word: "wrist", trans: "pergelangan", def: "Sendi perantara antara telapak dan lengan." }
    ],
    "A2 - Level 2": [
        { word: "address", trans: "alamat", def: "Keterangan letak domisili suatu tempat." },
        { word: "appear", trans: "muncul", def: "Mulai tampak kelihatan di depan mata." },
        { word: "arrive", trans: "tiba", def: "Sampai di tempat yang dituju." },
        { word: "cabbage", trans: "kubis", def: "Sayuran berdaun bulat padat berlapis." },
        { word: "collect", trans: "mengoleksi", def: "Menghimpun barang sejenis secara rapi." },
        { word: "correct", trans: "benar", def: "Sesuai fakta dan bebas kekeliruan." },
        { word: "difficult", trans: "sulit", def: "Memerlukan usaha ekstra untuk dipecahkan." },
        { word: "happen", trans: "terjadi", def: "Berlangsungnya peristiwa tanpa terduga sebelumnya." },
        { word: "luggage", trans: "koper bagasi", def: "Rangkaian muatan barang bawaan bepergian." },
        { word: "message", trans: "pesan", def: "Pemberitahuan yang dikirimkan ke pihak penerima." },
        { word: "mirror", trans: "cermin", def: "Kaca pemantul bayangan secara jernih." },
        { word: "narrow", trans: "sempit", def: "Ruang lajur yang tidak luas." },
        { word: "offer", trans: "menawarkan", def: "Menyodorkan barang agar diterima sukarela." },
        { word: "opposite", trans: "berlawanan", def: "Posisi berhadapan dengan arah berbeda." },
        { word: "passenger", trans: "penumpang", def: "Pemakai jasa layanan kendaraan umum." },
        { word: "pepper", trans: "lada", def: "Bumbu dapur pedas butir bulat." },
        { word: "pillow", trans: "bantal", def: "Pengganjal kepala empuk untuk tidur." },
        { word: "possible", trans: "mungkin", def: "Dapat terjadi secara nyata terlaksana." },
        { word: "puzzle", trans: "teka-teki", def: "Permainan mencocokkan potongan gambar logika." },
        { word: "ribbon", trans: "pita", def: "Sehelai kain pipih penghias kado." },
        { word: "robber", trans: "perampok", def: "Pelaku kejahatan penjarah harta benda." },
        { word: "shallow", trans: "dangkal", def: "Dasar perairan yang tidak dalam." },
        { word: "slipper", trans: "sandal", def: "Alas kaki santai dalam rumah." },
        { word: "sudden", trans: "tiba-tiba", def: "Berlangsung seketika tanpa peringatan awal." },
        { word: "support", trans: "mendukung", def: "Menyokong kelancaran program sampai tuntas." }
    ],
    "A2 - Level 3": [
        { word: "biscuit", trans: "biskuit", def: "Kue kering garing olahan tepung." },
        { word: "ceiling", trans: "langit-langit", def: "Bidang pembatas atas bagian ruangan." },
        { word: "creature", trans: "makhluk", def: "Segala ciptaan Tuhan yang bernyawa." },
        { word: "curtain", trans: "tirai", def: "Kain penghalang silau sinar jendela." },
        { word: "dangerous", trans: "berbahaya", def: "Berisiko mendatangkan kecelakaan fisik parah." },
        { word: "earn", trans: "mendapatkan", def: "Menerima upah atas hasil kerja." },
        { word: "famous", trans: "terkenal", def: "Dikenal luas khalayak karena keunggulan." },
        { word: "feather", trans: "bulu unggas", def: "Helaian penutup kulit tubuh burung." },
        { word: "fountain", trans: "air mancur", def: "Semburan air vertikal dari pipa." },
        { word: "heavy", trans: "berat", def: "Mempunyai bobot timbangan sangat masif." },
        { word: "journey", trans: "perjalanan", def: "Penjelajahan menuju rute tempat baru." },
        { word: "leather", trans: "kulit olahan", def: "Bahan lentur hasil penyamakan hewan." },
        { word: "mountain", trans: "gunung", def: "Bukit tanah bebatuan raksasa menjulang." },
        { word: "neighbour", trans: "tetangga", def: "Warga yang menghuni sekitar rumah." },
        { word: "ordinary", trans: "biasa", def: "Kondisi lazim tanpa ada keistimewaan." },
        { word: "piece", trans: "potongan", def: "Bagian belahan pecahan benda utuh." },
        { word: "pleasant", trans: "menyenangkan", def: "Menciptakan kesan riang dan nyaman." },
        { word: "receipt", trans: "kuitansi", def: "Lembar bukti sah transaksi pembayaran." },
        { word: "sauce", trans: "saus", def: "Cairan kental penambah cita rasa." },
        { word: "scissors", trans: "gunting", def: "Perkakas dua bilah pembelah kertas." },
        { word: "search", trans: "mencari", def: "Menelusuri lokasi demi menemukan objek." },
        { word: "shield", trans: "perisai", def: "Pelat penangkis senjata tajam musuh." },
        { word: "soldier", trans: "prajurit", def: "Anggota kesatuan militer pertahanan negara." },
        { word: "thief", trans: "pencuri", def: "Pengambil barang milik orang lain." },
        { word: "view", trans: "panorama", def: "Bentangan pemandangan alam terbuka bebas." }
    ],
    "B1 - Level 1": [
        { word: "ballet", trans: "tari balet", def: "Seni tarian teatrikal berteknik ketat." },
        { word: "buffet", trans: "prasmanan", def: "Penyajian aneka hidangan ambil mandiri." },
        { word: "calf", trans: "betis", def: "Bagian belakang kaki bawah lutut." },
        { word: "column", trans: "kolom", def: "Pilar penopang atau deret tegak." },
        { word: "depot", trans: "stasiun depo", def: "Tempat penyimpanan armada angkutan massal." },
        { word: "handsome", trans: "tampan", def: "Berparas elok bagi kaum pria." },
        { word: "hymn", trans: "kidung pujian", def: "Nyanyian kidung rohani pengagungan Tuhan." },
        { word: "knowledge", trans: "pengetahuan", def: "Kumpulan wawasan informasi yang dipelajari." },
        { word: "limb", trans: "anggota gerak", def: "Bagian lengan atau tungkai kaki." },
        { word: "mortgage", trans: "kredit rumah", def: "Pinjaman dana dengan jaminan properti." },
        { word: "plumber", trans: "tukang leding", def: "Teknisi perbaikan saluran perpipaan air." },
        { word: "rhythm", trans: "ritme", def: "Ketukan nada teratur dalam musik." },
        { word: "salmon", trans: "ikan salmon", def: "Ikan laut perenang migrasi sungai." },
        { word: "solemn", trans: "khidmat", def: "Suasana upacara hening dan sakral." },
        { word: "subtle", trans: "samar", def: "Perbedaan halus yang sukar disadari." },
        { word: "thumbprint", trans: "sidik jempol", def: "Cap garis sidik kulit ibu jari." },
        { word: "tomb", trans: "makam batu", def: "Bilik pusara pemakaman jasad kuno." },
        { word: "vehicle", trans: "kendaraan", def: "Sarana transportasi angkutan jalan raya." },
        { word: "yolk", trans: "kuning telur", def: "Zat kuning kaya nutrisi telur." },
        { word: "autumnal", trans: "khas gugur", def: "Berkaitan dengan masa musim gugur." },
        { word: "condemn", trans: "mengutuk", def: "Menyatakan kecaman keras terhadap pelanggaran." },
        { word: "debtor", trans: "debitur", def: "Pihak yang meminjam dana pinjaman." },
        { word: "doubtful", trans: "meragukan", def: "Belum teruji kepastian secara meyakinkan." },
        { word: "knuckle", trans: "buku jari", def: "Sendi engsel pembengkok ruas jari." },
        { word: "wreck", trans: "bangkai rongsok", def: "Kendaraan ringsek bekas dampak benturan." }
    ],
    "B1 - Level 2": [
        { word: "accommodate", trans: "mengakomodasi", def: "Menyediakan kamar fasilitas tempat tinggal." },
        { word: "aggressive", trans: "agresif", def: "Menunjukkan perilaku suka menyerang lawan." },
        { word: "announce", trans: "mengumumkan", def: "Menyampaikan warta resmi kepada khalayak." },
        { word: "apparent", trans: "terlihat nyata", def: "Tampak jelas dipahami tanpa praduga." },
        { word: "approve", trans: "menyetujui", def: "Memberi restu izin atas proposal." },
        { word: "assess", trans: "menilai", def: "Mengukur mutu performa pencapaian target." },
        { word: "challenge", trans: "tantangan", def: "Rintangan yang menguji kegigihan mental." },
        { word: "commit", trans: "berkomitmen", def: "Menjalankan kesepakatan janji secara bertanggungjawab." },
        { word: "committee", trans: "panitia", def: "Sekelompok tim pelaksana agenda perhelatan." },
        { word: "embarrass", trans: "mempermalukan", def: "Memicu canggung atau rasa malu." },
        { word: "grammar", trans: "tata bahasa", def: "Kaidah aturan baku susunan kalimat." },
        { word: "interrupt", trans: "menyela", def: "Memotong perkataan orang di percakapan." },
        { word: "necessary", trans: "perlu", def: "Syarat mutlak yang wajib ada." },
        { word: "occasion", trans: "kesempatan", def: "Momen perayaan acara waktu khusus." },
        { word: "occur", trans: "terjadi", def: "Berlangsungnya fakta pada kurun waktu." },
        { word: "parallel", trans: "sejajar", def: "Garis berdampingan lurus berjarak konstan." },
        { word: "possess", trans: "memiliki", def: "Menguasai kepemilikan benda secara sah." },
        { word: "recommend", trans: "menyarankan", def: "Mengajukan pilihan rujukan yang terbaik." },
        { word: "succeed", trans: "berhasil", def: "Meraih kejayaan dari impian terencana." },
        { word: "suggest", trans: "mengusulkan", def: "Memberikan masukan ide jalan keluar." },
        { word: "summarize", trans: "merangkum", def: "Memadatkan bahasan materi menjadi ringkas." },
        { word: "suppose", trans: "mengira", def: "Membuat perkiraan asumsi sementara waktu." },
        { word: "tomorrow", trans: "besok", def: "Satu hari setelah hari ini." },
        { word: "traffic", trans: "lalu lintas", def: "Alur kendaraan di jalanan kota." },
        { word: "village", trans: "perdesaan", def: "Kawasan hunian kecil penuh ketenangan." }
    ],
    "B1 - Level 3": [
        { word: "achieve", trans: "mencapai", def: "Menggapai sasaran tujuan dengan ikhtiar." },
        { word: "believe", trans: "percaya", def: "Meyakini kebenaran argumen pihak lain." },
        { word: "business", trans: "bisnis", def: "Sektor usaha niaga perdagangan komersial." },
        { word: "calendar", trans: "kalender", def: "Daftar penanggalan hari sepanjang tahun." },
        { word: "category", trans: "kategori", def: "Penggolongan kelompok berspesifikasi yang serupa." },
        { word: "decide", trans: "memutuskan", def: "Menetapkan satu pilihan final tindakan." },
        { word: "definite", trans: "pasti", def: "Tidak berubah dan bebas keraguan." },
        { word: "definitely", trans: "tentu saja", def: "Penegasan kesepakatan tanpa sanggahan sedikitpun." },
        { word: "environment", trans: "lingkungan", def: "Kondisi ekosistem alam sekitar kehidupan." },
        { word: "foreign", trans: "asing", def: "Berasal dari luar negeri bangsa." },
        { word: "guard", trans: "penjaga", def: "Petugas pengawal keselamatan gedung perkantoran." },
        { word: "guarantee", trans: "jaminan", def: "Garansi perlindungan mutu perbaikan barang." },
        { word: "jealous", trans: "cemburu", def: "Rasa iri atas keunggulan orang." },
        { word: "league", trans: "liga", def: "Ajang perserikatan kompetisi turnamen olahraga." },
        { word: "leisure", trans: "waktu luang", def: "Kesempatan bersantai rekreasi lepas beban." },
        { word: "machine", trans: "mesin", def: "Peralatan mekanik penunjang produksi industri." },
        { word: "niece", trans: "keponakan wanita", def: "Anak kandung saudara perempuan kandung." },
        { word: "persuade", trans: "membujuk", def: "Meyakinkan seseorang mengubah keputusannya sukarela." },
        { word: "privilege", trans: "hak istimewa", def: "Kelebihan perlakuan khusus kalangan tertentu." },
        { word: "queue", trans: "antrean", def: "Deretan antre memanjang menunggu giliran." },
        { word: "receive", trans: "menerima", def: "Mendapatkan titipan kiriman dari pengirim." },
        { word: "separate", trans: "memisahkan", def: "Membagi dua objek yang menempel." },
        { word: "surprise", trans: "kejutan", def: "Peristiwa dadakan yang bikin takjub." },
        { word: "weather", trans: "cuaca", def: "Kondisi udara pada waktu tertentu." },
        { word: "weird", trans: "aneh", def: "Berpenampilan ganjil menyimpang dari kewajaran." }
    ],
    "B2 - Level 1": [
        { word: "aisle", trans: "lorong lajur", def: "Jalur celah antara deretan bangku." },
        { word: "awkward", trans: "canggung", def: "Kikuk dalam berkomunikasi tatap muka." },
        { word: "benign", trans: "jinak", def: "Kondisi tumor yang tidak mematikan." },
        { word: "campaign", trans: "kampanye", def: "Gerakan promosi memenangkan suara rakyat." },
        { word: "debris", trans: "puing reruntuhan", def: "Serpihan pecahan pasca insiden ledakan." },
        { word: "drought", trans: "kekeringan", def: "Masa kemarau panjang defisit air." },
        { word: "exhaust", trans: "kelelahan", def: "Stamina terkuras habis akibat keletihan." },
        { word: "gauge", trans: "alat ukur", def: "Meteran presisi pemeriksa tekanan udara." },
        { word: "gnaw", trans: "menggerogoti", def: "Menggigit perlahan berulang memakai taring." },
        { word: "heir", trans: "ahli waris", def: "Penerima takhta sah titipan kekayaan." },
        { word: "indictment", trans: "dakwaan", def: "Tuduhan hukum perdata di pengadilan." },
        { word: "knight", trans: "ksatria", def: "Pendekar berkuda pelindung kerajaan kuno." },
        { word: "nuisance", trans: "gangguan", def: "Hal meresahkan yang memicu kejengkelan." },
        { word: "paradigm", trans: "paradigma", def: "Kerangka berpikir landasan ilmu pengetahuan." },
        { word: "pneumonia", trans: "paru-paru basah", def: "Radang kantong pernapasan akibat kuman." },
        { word: "reign", trans: "bertahta", def: "Menjalankan mandat kepemimpinan tahta raja." },
        { word: "resign", trans: "mundur kerja", def: "Berhenti berkarier atas kehendak sendiri." },
        { word: "sovereignty", trans: "kedaulatan", def: "Hak kekuasaan tertinggi memimpin wilayah." },
        { word: "thorough", trans: "saksama", def: "Meneliti cermat terperinci tanpa terlewat." },
        { word: "threshold", trans: "ambang batas", def: "Tolak ukur minimal memulai perubahan." },
        { word: "yacht", trans: "kapal pesiar", def: "Kapal mewah pribadi penjelajah lautan." },
        { word: "knack", trans: "keahlian unik", def: "Bakat alami menuntaskan tugas rumit." },
        { word: "solemnity", trans: "kesakralan", def: "Nuansa hikmat pada acara suci." },
        { word: "subtlely", trans: "secara halus", def: "Dikerjakan perlahan nyaris tak terlihat." },
        { word: "wrestle", trans: "bergulat", def: "Bertarung menjatuhkan musuh ke matras." }
    ],
    "B2 - Level 2": [
        { word: "accessible", trans: "mudah diakses", def: "Gampang diraih oleh semua pengguna." },
        { word: "accidentally", trans: "tanpa sengaja", def: "Berlangsung di luar kehendak niat." },
        { word: "apparatus", trans: "aparatus alat", def: "Perangkat instrumen laboratorium riset ilmiah." },
        { word: "appropriate", trans: "pantas", def: "Serasi dengan etika kaidah setempat." },
        { word: "colleague", trans: "rekan sejawat", def: "Kawan satu profesi di kantor." },
        { word: "commission", trans: "komisi", def: "Penugasan wewenang atau pembagian keuntungan." },
        { word: "commitment", trans: "komitmen", def: "Ikrar dedikasi penuh menyelesaikan tujuan." },
        { word: "disappoint", trans: "mengecewakan", def: "Gagal memenuhi harapan pihak kawan." },
        { word: "exaggerate", trans: "melebih-lebihkan", def: "Membesar-besarkan uraian cerita dari kenyataan." },
        { word: "harass", trans: "melecehkan", def: "Mengganggu martabat pihak lain agresif." },
        { word: "hierarchy", trans: "hierarki", def: "Tingkatan strata kepangkatan struktur organisasi." },
        { word: "illuminate", trans: "menerangi", def: "Memancarkan cahaya cerah ke sudut." },
        { word: "immediate", trans: "segera", def: "Harus dieksekusi instan tanpa tunda." },
        { word: "irresistible", trans: "tak tertolak", def: "Daya pikat mempesona sukar dicegah." },
        { word: "millennium", trans: "milenium", def: "Periode waktu berdurasi seribu tahun." },
        { word: "omission", trans: "penghilangan", def: "Tindakan mencoret unsur dari daftar." },
        { word: "oscillate", trans: "berosilasi", def: "Berayun bolak-balik melintasi titik." },
        { word: "questionnaire", trans: "angket", def: "Kumpulan butir pertanyaan survei opini." },
        { word: "rebellion", trans: "pemberontakan", def: "Gerakan penentangan otoritas penguasa lalim." },
        { word: "surveillance", trans: "pengawasan", def: "Pemantauan aktivitas target secara rahasia." },
        { word: "symmetry", trans: "kesimetrisan", def: "Keseimbangan proporsi wujud kedua sisi." },
        { word: "tariff", trans: "bea masuk", def: "Pungutan pajak terhadap komoditas impor." },
        { word: "unnecessary", trans: "tidak perlu", def: "Pemborosan hal yang tidak berguna." },
        { word: "withhold", trans: "menahan", def: "Menunda menyalurkan hak milik pihak." },
        { word: "disciplinary", trans: "kedisiplinan", def: "Penegakan sanksi tata tertib institusi." }
    ],
    "B2 - Level 3": [
        { word: "acquaintance", trans: "kenalan", def: "Orang yang dikenal sekilas muka." },
        { word: "amateur", trans: "amatir", def: "Penyalur hobi non-pekerja bayaran." },
        { word: "athlete", trans: "atlet", def: "Olahragawan tangguh pengukir rekor kejuaraan." },
        { word: "catastrophe", trans: "malapetaka", def: "Bencana dahsyat pemusnah tatanan wilayah." },
        { word: "cemetery", trans: "pemakaman", def: "Lahan perkuburan tempat mengubur jenazah." },
        { word: "conscience", trans: "hati nurani", def: "Kompas moral pembeda baik buruk." },
        { word: "conscious", trans: "sadar", def: "Menyadari eksistensi raga secara waras." },
        { word: "counterfeit", trans: "palsu", def: "Barang tiruan perusak peredaran uang." },
        { word: "courteous", trans: "santun", def: "Berbudi bahasa ramah kepada sesama." },
        { word: "grievance", trans: "keluhan", def: "Aspirasi ketidakpuasan atas ketidakadilan kerja." },
        { word: "humorous", trans: "jenaka", def: "Mengandung gurauan yang memancing gelak." },
        { word: "liaison", trans: "penghubung", def: "Fasilitator koordinasi perwakilan antar instansi." },
        { word: "maintenance", trans: "pemeliharaan", def: "Perawatan alat mekanis secara berkala." },
        { word: "mischievous", trans: "jahil", def: "Suka berbuat ulah keisengan sepele." },
        { word: "noticeable", trans: "kentara", def: "Gampang diamati karena mencolok perbedaannya." },
        { word: "perseverance", trans: "ketekunan", def: "Keuletan berjuang melewati badai ujian." },
        { word: "playwright", trans: "penulis drama", def: "Penyusun skenario naskah lakon panggung." },
        { word: "prejudice", trans: "prasangka", def: "Penilaian apriori tanpa menyelidiki fakta." },
        { word: "pronunciation", trans: "pelafalan", def: "Ketepatan membunyikan fonem artikulasi lidah." },
        { word: "recipient", trans: "penerima", def: "Pihak tujuan sampainya bingkisan paket." },
        { word: "twelfth", trans: "kedua belas", def: "Urutan ranking tepat setelah kesebelas." },
        { word: "vengeance", trans: "dendam", def: "Niat pembalasan setimpal atas sakit." },
        { word: "villain", trans: "penjahat", def: "Karakter antagonis pemicu konflik panggung." },
        { word: "vulnerable", trans: "rentan", def: "Mudah terpapar ancaman bahaya fisik." },
        { word: "yield", trans: "menghasilkan", def: "Menghasilkan panen keuntungan atau komoditas." }
    ],
    "C1 - Level 1": [
        { word: "acquiesce", trans: "pasrah setuju", def: "Menuruti putusan tanpa protes terbuka." },
        { word: "aesthetic", trans: "estetis", def: "Sentuhan nilai keindahan rasa visual." },
        { word: "anaesthetic", trans: "obat bius", def: "Zat mati rasa operasi medis." },
        { word: "bourgeois", trans: "borjuis", def: "Golongan mapan pemilik modal sosial." },
        { word: "camouflage", trans: "kamuflase", def: "Trik penyamaran rona tubuh alam." },
        { word: "chasm", trans: "jurang pemisah", def: "Ngarai celah jurang pemisah bebatuan." },
        { word: "chassis", trans: "rangka mobil", def: "Kerangka baja tumpuan mesin mobil." },
        { word: "faux pas", trans: "kekeliruan etiket", def: "Keteledoran melanggar adat istiadat sosial." },
        { word: "feign", trans: "berpura-pura", def: "Memalsukan ekspresi demi mengelabui lawan." },
        { word: "fraught", trans: "penuh tekanan", def: "Situasi genting diselimuti kekhawatiran besar." },
        { word: "heinous", trans: "keji", def: "Perbuatan kriminal biadab di luar batas." },
        { word: "opaque", trans: "buram", def: "Material pekat yang kedap cahaya." },
        { word: "phlegm", trans: "dahak", def: "Cairan lendir kental saluran pernapasan." },
        { word: "poignant", trans: "mengharukan", def: "Menyentuh kalbu hingga menguras empati." },
        { word: "pseudonym", trans: "nama samaran", def: "Nama alias kepenulisan buku sastra." },
        { word: "psalm", trans: "mazmur", def: "Lantunan gita kidung doa sakral." },
        { word: "rendezvous", trans: "titik temu", def: "Pertemuan di lokasi yang disepakati." },
        { word: "rhetoric", trans: "retorika", def: "Seni olah vokal meyakinkan audiens." },
        { word: "succinct", trans: "padat ringkas", def: "Penyampaian inti pikiran tanpa tele-tele." },
        { word: "vignette", trans: "sketsa miniatur", def: "Cuplikan deskripsi adegan drama puitis." },
        { word: "wrought", trans: "ditempa", def: "Besi yang ditempa seni ukir." },
        { word: "subpoena", trans: "surat panggilan", def: "Panggilan paksa menghadiri sidang perkara." },
        { word: "sojourn", trans: "singgah singgah", def: "Tinggal bermukim sementara waktu tertentu." },
        { word: "schism", trans: "perpecahan kubu", def: "Pecahnya persatuan partai menjadi sekte." },
        { word: "paradox", trans: "paradoks", def: "Dua pernyataan kontradiktif memuat kebenaran." }
    ],
    "C1 - Level 2": [
        { word: "aggravate", trans: "memperparah", def: "Membuat kondisi genting kian runyam." },
        { word: "ancillary", trans: "penunjang", def: "Elemen penopang kelancaran sistem utama." },
        { word: "cappuccino", trans: "kapucino", def: "Kopi espreso berpadu busa susu." },
        { word: "corroboration", trans: "penguatan bukti", def: "Penyelarasan bukti pendukung fakta pengadilan." },
        { word: "desiccate", trans: "mengeringkan", def: "Menguras kelembapan air hingga kerontang." },
        { word: "dilettante", trans: "pencinta seni awam", def: "Peminat seni tanpa keahlian mendalam." },
        { word: "disassemble", trans: "membongkar", def: "Mengurai suku cadang mesin komponen." },
        { word: "drunkenness", trans: "kemabukan", def: "Kondisi hilang kendali terbius alkohol." },
        { word: "embarrassment", trans: "rasa malu", def: "Beban kikuk akibat insiden tercela." },
        { word: "flabbergasted", trans: "tercengang", def: "Terguncang kaget mendapati kabar mengejutkan." },
        { word: "haemorrhage", trans: "pendarahan", def: "Kebocoran cairan darah pembuluh pecah." },
        { word: "innocuous", trans: "tidak berbahaya", def: "Benda netral yang bebas racun." },
        { word: "mayonnaise", trans: "mayones", def: "Saus emulsi kuning telur gurih." },
        { word: "misspell", trans: "salah mengeja", def: "Keliru menuliskan susunan abjad kata." },
        { word: "obsessive", trans: "obsesif", def: "Gandrung ekstrem berlebih pada objek." },
        { word: "occurrence", trans: "kejadian nyata", def: "Peristiwa yang sedang berlangsung kini." },
        { word: "oscillation", trans: "osilasi gerak", def: "Frekuensi getaran gelombang medan magnet." },
        { word: "reconnaissance", trans: "pengintaian militer", def: "Penyelidikan wilayah medan taktik pertempuran." },
        { word: "satellite", trans: "satelit", def: "Wahana antariksa pemancar sinyal komunikasi." },
        { word: "scintillating", trans: "berkilauan tajam", def: "Pintar jenius memukau banyak pemirsa." },
        { word: "surreptitious", trans: "diam-diam", def: "Dilakukan sembunyi menjauhi sorotan mata." },
        { word: "tyrannical", trans: "lalim bertangan besi", def: "Kekuasaan otoriter menindas kebebasan sipil." },
        { word: "unparalleled", trans: "tanpa tandingan", def: "Prestasi gemilang nomor satu dunia." },
        { word: "vacillate", trans: "bimbang goyah", def: "Ragu memilih keputusan masa depan." },
        { word: "whippoorwill", trans: "burung malam", def: "Spesies burung pemangsa serangga petang." }
    ],
    "C1 - Level 3": [
        { word: "aberration", trans: "anomali", def: "Penyimpangan tajam dari kaidah normal." },
        { word: "asynchronous", trans: "asinkron", def: "Komunikasi dua arah berselisih waktu." },
        { word: "connoisseur", trans: "penikmat ahli", def: "Kolektor seni berkepekaan rasa tinggi." },
        { word: "conscientious", trans: "penuh kehati-hatian", def: "Bekerja tertib dipandu etika profesional." },
        { word: "idiosyncrasy", trans: "keanehan watak", def: "Tabiat unik personal seseorang figur." },
        { word: "inadvertent", trans: "tanpa sengaja", def: "Terlaksana akibat kelengahan tanpa sadar." },
        { word: "maneuver", trans: "manuver taktis", def: "Gerakan cerdik mengatasi hambatan jalan." },
        { word: "mnemonic", trans: "jembatan keledai", def: "Metode hafalan pemacu memori otak." },
        { word: "nauseous", trans: "mual pusing", def: "Gejala perut bergejolak ingin muntah." },
        { word: "obsequious", trans: "penjilat muka", def: "Merendah berlebihan demi keuntungan pamrih." },
        { word: "panacea", trans: "obat mujarab", def: "Solusi serbaguna penuntas semua komplikasi." },
        { word: "paraphernalia", trans: "pernak-pernik", def: "Perkakas pelengkap kegiatan ritual tertentu." },
        { word: "pharmaceutical", trans: "farmasi obat", def: "Sektor riset produksi obat kimia." },
        { word: "quintessential", trans: "perwujudan sejati", def: "Contoh paling sempurna di kelasnya." },
        { word: "sacrilegious", trans: "menodai agama", def: "Menghina simbol-simbol kesucian tempat ibadah." },
        { word: "scrupulous", trans: "sangat cermat", def: "Pemeriksaan detail tanpa celah kebocoran." },
        { word: "silhouette", trans: "siluet bayangan", def: "Bayangan hitam kontras berlatar terang." },
        { word: "spontaneity", trans: "spontanitas", def: "Reaksi reflek tanpa rekayasa naskah." },
        { word: "supersede", trans: "menggantikan", def: "Menggeser ketetapan usang aturan kuno." },
        { word: "ubiquitous", trans: "ada di mana-mana", def: "Hadir merata di seantero penjuru." },
        { word: "veterinarian", trans: "dokter hewan", def: "Pakar medis klinis pengobat fauna." },
        { word: "bureaucracy", trans: "birokrasi", def: "Sistem tata kelola berjenjang rumit." },
        { word: "surveillance", trans: "pemantauan ketat", def: "Pengawasan intelijen atas aksi tersangka." },
        { word: "inaccessible", trans: "tak terjangkau", def: "Medan pedalaman yang terisolasi transportasi." },
        { word: "queueing", trans: "mengantre", def: "Berbaris berurutan menanti jatah giliran." }
    ],
    "C2 - Level 1": [
        { word: "bdellium", trans: "damar wangi", def: "Getah dupa kering peribadatan kuno." },
        { word: "chiaroscuro", trans: "kontras bayangan", def: "Gradasi gelap terang lukisan renaisans." },
        { word: "czar", trans: "tsar kaisar", def: "Gelar monarki imperium Rusia masa." },
        { word: "demagogue", trans: "penghasut massa", def: "Orator penyulut emosi prasangka kebencian." },
        { word: "diaphanous", trans: "tembus pandang halus", def: "Kain sutra tipis melayang transparan." },
        { word: "gnathic", trans: "berkaitan rahang", def: "Anatomi tulang geligi rahang tengkorak." },
        { word: "impugn", trans: "meragukan integritas", def: "Menyerang kejujuran kesaksian saksi ahli." },
        { word: "phlegmatic", trans: "berwatak dingin", def: "Pembawaan kalem tidak mudah terprovokasi." },
        { word: "phthisis", trans: "tuberkulosis akut", def: "Infeksi penyakit pengeropos organ paru-paru." },
        { word: "pique", trans: "kejengkelan gengsi", def: "Tersinggung harga diri akibat dipermalukan." },
        { word: "pshaw", trans: "cih ungkapan", def: "Seruan mencemooh pendapat yang remeh." },
        { word: "ptarmigan", trans: "burung arktika", def: "Unggas salju berbulu putih kamuflase." },
        { word: "pterodactyl", trans: "reptil terbang purba", def: "Dinosaurus bersayap membran zaman prasejarah." },
        { word: "quay", trans: "dermaga kapal", def: "Tepian beton pelabuhan sandar kargo." },
        { word: "synecdoche", trans: "sinekdoke", def: "Gaya bahasa sebut bagian mewakili." },
        { word: "viceroy", trans: "raja muda perwakilan", def: "Gubernur penguasa daerah koloni jajahan." },
        { word: "vraisemblance", trans: "kemiripan realitas", def: "Kemiripan karya fiksi mendekati kenyataan." },
        { word: "xenophobia", trans: "benci orang asing", def: "Ketakutan tak rasional imigran pendatang." },
        { word: "zeitgeist", trans: "jiwa zaman", def: "Karakter semangat budaya kurun masa." },
        { word: "apotheosis", trans: "puncak pendewaan", def: "Titik klimaks pemuliaan seorang tokoh." },
        { word: "mnemonic", trans: "mnemonik memori", def: "Trik asupan asosiasi pengingat istilah." },
        { word: "colonel", trans: "kolonel perwira", def: "Perwira militer di bawah jenderal." },
        { word: "indictment", trans: "dakwaan resmi", def: "Berkas tuduhan pidana jaksa agung." },
        { word: "draughtsman", trans: "juru gambar rancang", def: "Arsitek pembuat cetak biru bangunan." },
        { word: "sovereignty", trans: "kedaulatan negara", def: "Kekuasaan otonom penuh tanpa intervensi." }
    ],
    "C2 - Level 2": [
        { word: "abscess", trans: "bisul bernanah", def: "Kantung infeksi bakteri pembengkakan jaringan." },
        { word: "arrhythmia", trans: "aritmia jantung", def: "Denyut detak jantung tidak beraturan." },
        { word: "baccalaureate", trans: "ijazah sarjana muda", def: "Kualifikasi kelulusan tingkat perguruan tinggi." },
        { word: "bellwether", trans: "indikator penentu", def: "Perintis tolak ukur tren pergerakan." },
        { word: "cachet", trans: "prestise martabat", def: "Daya wibawa terpandang status terhormat." },
        { word: "diphtheria", trans: "difteri infeksi", def: "Penyakit selaput lendir tenggorokan berbahaya." },
        { word: "focaccia", trans: "roti fokasia", def: "Roti panggangan herbal minyak zaitun." },
        { word: "fuchsia", trans: "merah fusi", def: "Rona ungu kemerahan bunga hias." },
        { word: "gubernatorial", trans: "kekuasaan gubernur", def: "Hal menyangkut pemilihan kepemimpinan gubernur." },
        { word: "logorrhoea", trans: "kelancangan bertutur", def: "Keluarnya kata-kata secara bertubi-tubi berlebihan." },
        { word: "marshmallow", trans: "manisan kenyal", def: "Gula busa lembut legit kenyal." },
        { word: "obbligato", trans: "iringan wajib nada", def: "Melodi pengiring vital instrumen musik." },
        { word: "panegyric", trans: "pujian resmi", def: "Pidato pengagungan prestasi kepahlawanan mendiang." },
        { word: "picnicking", trans: "berpiknik santai", def: "Kegiatan bersantap bekal di taman." },
        { word: "syzygy", trans: "oposisi tiga planet", def: "Kesejajaran garis tiga benda antariksa." },
        { word: "tintinnabulation", trans: "gemerincing lonceng", def: "Dentingan dering bunyi genta bergema." },
        { word: "bourgeoisie", trans: "kaum borjuis", def: "Golongan masyarakat pemegang dominasi ekonomi." },
        { word: "reconnoitre", trans: "memantau medan", def: "Menelisik posisi posko persembunyian musuh." },
        { word: "convalescence", trans: "masa pemulihan", def: "Periode penyembuhan raga pasca operasi." },
        { word: "iridescent", trans: "berkilau pelangi", def: "Kilau perubahan pantulan spektrum prisma." },
        { word: "recalcitrant", trans: "pembangkang bebal", def: "Keras kepala menentang instruksi pimpinan." },
        { word: "effervescence", trans: "buih mendidih", def: "Pelepasan gelembung gas larutan cair." },
        { word: "idiosyncratic", trans: "berkarakter eksentrik", def: "Memiliki tabiat pribadi menyimpang lazim." },
        { word: "surreptitiousness", trans: "kerahasiaan gerak", def: "Aksi gerak senyap menghindari pengawasan." },
        { word: "paraphernalia", trans: "peralatan ritual", def: "Kelengkapan atribut upacara penobatan keraton." }
    ],
    "C2 - Level 3": [
        { word: "antediluvian", trans: "kuno purbakala", def: "Zaman lampau sebelum banjir bah." },
        { word: "asphyxiation", trans: "mati lemas", def: "Tersumbatnya pasokan oksigen menuju paru-paru." },
        { word: "cacophony", trans: "suara sumbang bingar", def: "Kekacauan bebunyian bising memekakkan telinga." },
        { word: "catachresis", trans: "penyimpangan kiasan", def: "Penyalahgunaan metafora perbandingan janggal bahasa." },
        { word: "chamomile", trans: "kamomil herba", def: "Bunga aromatik penyeduh teh penenang." },
        { word: "chimerical", trans: "khayalan mustahil", def: "Imajinasi fiktif utopis tanpa kenyataan." },
        { word: "hors d'oeuvre", trans: "makanan pembuka", def: "Porsi kudapan penyegar santapan utama." },
        { word: "lachrymose", trans: "mudah berlinang air mata", def: "Cenderung cengeng terhanyut ratap duka." },
        { word: "liqueur", trans: "minuman likur", def: "Minuman suling manis beralkohol kental." },
        { word: "onomatopoeia", trans: "tiruan bunyi", def: "Kata pembentuk tiruan suara alam." },
        { word: "ophthalmologist", trans: "dokter spesialis mata", def: "Ahli bedah penanganan penyakit retina." },
        { word: "panoply", trans: "busana kebesaran", def: "Deretan koleksi atribut kemegahan lengkap." },
        { word: "pharaoh", trans: "firaun penguasa", def: "Raja monarki dinasti lembah Nil." },
        { word: "psychiatrist", trans: "psikiater jiwa", def: "Dokter penanganan gangguan kejiwaan klinis." },
        { word: "schadenfreude", trans: "senang rival celaka", def: "Kepuasan terselubung mengamati penderitaan lawan." },
        { word: "tchotchke", trans: "pajangan murah", def: "Suvenir mungil tanpa fungsi guna." },
        { word: "vicissitude", trans: "pasang surut nasib", def: "Gejolak perputaran peruntungan siklus duniawi." },
        { word: "weltschmerz", trans: "kegalauan eksistensial", def: "Kelesuan jiwa menatap ketidaksempurnaan dunia." },
        { word: "bourgeois", trans: "kaum menengah atas", def: "Warga mapan pemburu kenikmatan materi." },
        { word: "manoeuvre", trans: "manuver gesit", def: "Taktik lincah mengecoh kepungan lawan." },
        { word: "bureaucracy", trans: "tata kelola birokrasi", def: "Rantai prosedur perizinan instansi pemerintah." },
        { word: "psychosis", trans: "psikosis halusinasi", def: "Disorientasi mental lepas dari realitas." },
        { word: "haemorrhage", trans: "pendarahan hebat", def: "Aliran darah bocor dari pembuluh." },
        { word: "connoisseur", trans: "pakar seni cita rasa", def: "Penilai mahakarya seni bernilai langka." },
        { word: "silhouette", trans: "garis bentuk bayang", def: "Kontur wujud hitam menentang silau." }
    ]
};